inherit_from:
  - internal/style_guide.yml
  - internal/rails_style_guide.yml
  - internal/overrides.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - db/schema.rb

Rails/OutputSafety:
  Enabled: false
