Bundler/OrderedGems:
  Enabled: false

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/AbcSize:
  Exclude:
    - test/**/*_test.rb

Metrics/LineLength:
  Exclude:
    - db/migrate/**/*
  IgnoredPatterns:
    - !ruby/regexp /^\s*#/

Metrics/BlockLength:
  Exclude:
    - config/initializers/**/*
    - config/environments/**/*
    - lib/tasks/**/*.rake
    - "**/*.gemspec"

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*_test.rb
    - db/migrate/**/*

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*_test.rb

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/WhileUntilModifier:
  Enabled: false
