---
Rails/DynamicFindBy:
  Description: Use `find_by` instead of dynamic `find_by_*`.
  StyleGuide: https://github.com/bbatsov/rails-style-guide#find_by
  Enabled: true
  Whitelist:
  - find_by_sql
Rails/FindBy:
  Description: Prefer find_by over where.first.
  StyleGuide: https://github.com/bbatsov/rails-style-guide#find_by
  Enabled: true
  Include:
  - app/models/**/*.rb
Rails/FindEach:
  Description: Prefer all.find_each over all.find.
  StyleGuide: https://github.com/bbatsov/rails-style-guide#find-each
  Enabled: true
  Include:
  - app/models/**/*.rb
Rails/HasAndBelongsToMany:
  Description: Prefer has_many :through to has_and_belongs_to_many.
  StyleGuide: https://github.com/bbatsov/rails-style-guide#has-many-through
  Enabled: true
  Include:
  - app/models/**/*.rb
Rails/ReadWriteAttribute:
  Description: Checks for read_attribute(:attr) and write_attribute(:attr, val).
  StyleGuide: https://github.com/bbatsov/rails-style-guide#read-attribute
  Enabled: true
  Include:
  - app/models/**/*.rb
Rails/ReversibleMigration:
  Description: Checks whether the change method of the migration file is reversible.
  StyleGuide: https://github.com/bbatsov/rails-style-guide#reversible-migration
  Reference: http://api.rubyonrails.org/classes/ActiveRecord/Migration/CommandRecorder.html
  Enabled: true
  Include:
  - db/migrate/*.rb
Rails/TimeZone:
  Description: Checks the correct usage of time zone aware methods.
  StyleGuide: https://github.com/bbatsov/rails-style-guide#time
  Reference: http://danilenko.org/2012/7/6/rails_timezones
  Enabled: true
  EnforcedStyle: flexible
  SupportedStyles:
  - strict
  - flexible
